### PR TITLE
fix: added if(mounted) to all setState

### LINKED ISSUE #16: setState is being called on a deactivated widget
At many places setState has been called but the widget is already removed from the widget tree. Due to this, the application that uses the package shows grey screen in release mode.

Screenshots:
image

### PR DESCRIPTION
**Pull request by AbhishekDoshi26**
fix: Fixed keys to use the latest conventions
fix: added if(mounted) to all setState

This PR fix #16

### CODE REVIEW

**Comment by AbhishekDoshi26** [comment]
@SankethBK it would be great if you merge this and publish a new version. We are using your package in a production app and this is a critical bug.

Thanks!

**Comment by SankethBK** [comment]
I see this is a valid usescase, I assumed SessionTimeoutManager will always be at root of the widget tree and can never get mounted, but this may not be the case always. Thanks for the contribution

**Review by SankethBK — APPROVED** [review]
LGTM

**Comment by AbhishekDoshi26** [comment]
Thanks 🙌🏻 
It would be great if a new version of package is published. Otherwise I will have to use my git version 😓

**Comment by SankethBK** [comment]
Published 👍

**Pull request merged**
